title: "한국사 기록 채널"
title_separator: "-"
subtitle: "잊혀진 역사, 기억할 시간"
name: "korea-history"
description: "한국의 역사와 인물들을 기록하고 소개하는 채널입니다."
url: "https://korea-history.github.io"
baseurl: "/myhistorykorea1" # 저장소 이름
repository: "korea-history/myhistorykorea1"

minimal_mistakes_skin: "default"
locale: "ko-KR"

author:
  name: "korea-history"
  bio: "한국사를 사랑하고 기록하는 사람입니다."
  location: "South Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/korea-history"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/korea-history"

theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
